import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://oreag.vercel.app"),
  title: "Oreag — RAG & Memory as a Service",
  description:
    "Turn your documents into a queryable RAG API with a built-in memory graph: upload, tune chunking and embeddings, and get a per-project endpoint.",
  // Favicons are picked up from the app/ file conventions: icon.svg + favicon.ico
  // The OG/Twitter image is generated by app/opengraph-image.tsx.
  openGraph: {
    title: "Oreag — RAG & Memory as a Service",
    description:
      "Turn your documents into a queryable RAG API with a built-in memory graph.",
    url: "/",
    siteName: "Oreag",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Oreag — RAG & Memory as a Service",
    description:
      "Turn your documents into a queryable RAG API with a built-in memory graph.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          {children}
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
