"""Render every Supabase auth email from ONE theme.

WHY A GENERATOR RATHER THAN FIVE HAND-EDITED FILES

Because the drift already bit. `reset-password.html` and `confirm-signup.html`
were restyled and both lost - or never had - the `{{ .Token }}` placeholder,
while the app had moved to asking people to TYPE a code. The emails arrived
looking correct and carrying only a link, so every code field in the product
had nothing to fill it with. Five near-identical files invite exactly that: the
theme gets updated in one and the tokens in another.

Run:  python scripts/build_email_templates.py
Then paste each file into Supabase → Authentication → Email Templates.

WHICH APP CALL USES WHICH TEMPLATE - get this wrong and the right-looking email
is sent for the wrong flow:

  signUp()                      -> Confirm signup    (confirmation)
  signInWithOtp()               -> Magic Link        (magic_link)
  resetPasswordForEmail()       -> Reset Password    (recovery)
  reauthenticate()              -> Reauthentication  (reauthentication)
  updateUser({email})           -> Change Email      (email_change)

TOKENS, AND THE ONE THAT IS DIFFERENT

`{{ .Token }}` is the typed code and belongs in EVERY template - the product
offers a code path for all of them.

`{{ .TokenHash }}` builds a one-click link into /auth/confirm. Deliberately NOT
`{{ .ConfirmationURL }}`: that routes through Supabase's verify endpoint and
hands back a PKCE `?code=`, which only works in the browser that STARTED the
flow. Request on a laptop, open on a phone, and it fails.

REAUTHENTICATION HAS NO LINK. Supabase issues a bare nonce for it - there is no
TokenHash and no ConfirmationURL - so that template is code-only. Putting a link
in it produces a dead href, which is why it gets its own branch below rather
than an "optional" flag nobody would notice was off.
"""
from __future__ import annotations

import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "supabase" / "templates"

# One shared shell. Colours and radii match frontend/src/app globals so the mail
# and the app look like the same product.
SHELL = """<!--
  Oreag - "{dashboard_name}" email template.

  Paste into: Supabase Dashboard -> Authentication -> Email Templates ->
  "{dashboard_name}".  Subject:  {subject}

  GENERATED by scripts/build_email_templates.py - edit that, not this file.
  {token_note}
-->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f5;margin:0;padding:24px 0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <tr>
    <td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background-color:#ffffff;border:1px solid #e4e4e7;border-radius:14px;overflow:hidden;">
        <tr>
          <td align="center" style="padding:32px 32px 8px 32px;">
            <img src="{{{{ .SiteURL }}}}/logo.png" width="48" height="48" alt="Oreag" style="display:block;border-radius:10px;" />
            <div style="margin-top:12px;font-size:20px;font-weight:700;letter-spacing:-0.02em;color:#0a0a0a;">Oreag</div>
            <div style="font-size:13px;color:#71717a;">RAG &amp; Memory as a Service</div>
          </td>
        </tr>

        <tr>
          <td style="padding:16px 32px 8px 32px;">
            <h1 style="margin:0 0 12px 0;font-size:22px;font-weight:700;color:#0a0a0a;text-align:center;">{heading}</h1>
            <p style="margin:0 0 24px 0;font-size:15px;line-height:1.6;color:#3f3f46;text-align:center;">
              {lead}
            </p>
          </td>
        </tr>

        <tr>
          <td align="center" style="padding:0 32px 4px 32px;">
            <div style="font-size:12px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:#71717a;">
              {code_label}
            </div>
            <div style="margin:10px 0 0 0;padding:14px 20px;background-color:#fafafa;border:1px solid #e4e4e7;border-radius:10px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:30px;font-weight:700;letter-spacing:10px;color:#0a0a0a;">{{{{ .Token }}}}</div>
            <p style="margin:10px 0 0 0;font-size:12px;line-height:1.6;color:#a1a1aa;">
              Expires shortly and can only be used once.
            </p>
          </td>
        </tr>
{link_section}
        <tr>
          <td style="padding:28px 32px 32px 32px;">
            <hr style="border:none;border-top:1px solid #e4e4e7;margin:0 0 16px 0;" />
            <p style="margin:0;font-size:12px;line-height:1.6;color:#a1a1aa;text-align:center;">
              {reassurance}
            </p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
"""

# Rendered only for templates that HAVE a token hash. The divider carries its
# own "or" so the code and the link read as alternatives rather than steps.
LINK_SECTION = """
        <tr>
          <td align="center" style="padding:22px 32px 0 32px;">
            <div style="font-size:12px;color:#a1a1aa;">or</div>
          </td>
        </tr>

        <tr>
          <td align="center" style="padding:14px 32px 8px 32px;">
            <table role="presentation" cellpadding="0" cellspacing="0">
              <tr>
                <td align="center" bgcolor="#0a0a0a" style="border-radius:10px;">
                  <a href="{link}"
                     style="display:inline-block;padding:13px 32px;font-size:15px;font-weight:600;color:#ffffff;text-decoration:none;border-radius:10px;">
                    {cta} &rarr;
                  </a>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td style="padding:20px 32px 0 32px;">
            <p style="margin:0;font-size:12px;line-height:1.6;color:#a1a1aa;text-align:center;">
              Button not working? Paste this link into your browser:
            </p>
            <p style="margin:6px 0 0 0;font-size:12px;line-height:1.5;color:#3f3f46;text-align:center;word-break:break-all;">
              <a href="{link}" style="color:#2563eb;text-decoration:underline;">{link}</a>
            </p>
          </td>
        </tr>
"""


def _link(otp_type: str, next_path: str) -> str:
    return (
        "{{ .SiteURL }}/auth/confirm"
        f"?token_hash={{{{ .TokenHash }}}}&type={otp_type}&next={next_path}"
    )


TEMPLATES = {
    "confirm-signup.html": dict(
        dashboard_name="Confirm signup",
        subject="Confirm your Oreag email",
        heading="Confirm your email",
        lead="Enter this code to finish setting up your Oreag account.",
        code_label="Confirmation code",
        otp_type="signup",
        next_path="/dashboard",
        cta="Confirm my email",
        reassurance=(
            "Didn&rsquo;t create an Oreag account? You can ignore this email - "
            "nothing is created unless the code or link is used."
        ),
    ),
    "magic-link.html": dict(
        dashboard_name="Magic Link",
        subject="Your Oreag sign-in code",
        heading="Your sign-in code",
        lead=(
            "Enter this code to finish signing in. We ask for it when your "
            "account has no passkey or authenticator app."
        ),
        code_label="Sign-in code",
        otp_type="magiclink",
        next_path="/dashboard",
        cta="Sign in with one click",
        reassurance=(
            "Didn&rsquo;t try to sign in? You can ignore this email - your "
            "account is safe, and nothing changes unless the code or link is "
            "used."
        ),
    ),
    "reset-password.html": dict(
        dashboard_name="Reset Password",
        subject="Reset your Oreag password",
        heading="Reset your password",
        lead="Enter this code to set a new password for your Oreag account.",
        code_label="Reset code",
        otp_type="recovery",
        next_path="/auth/reset-password",
        cta="Reset my password",
        reassurance=(
            "If you didn&rsquo;t request a password reset, you can safely "
            "ignore this email - your password won&rsquo;t change."
        ),
    ),
    "email-change.html": dict(
        dashboard_name="Change Email Address",
        subject="Confirm your new Oreag email",
        heading="Confirm your new email",
        lead="Enter this code to confirm the new address on your account.",
        code_label="Confirmation code",
        otp_type="email_change",
        next_path="/settings/profile",
        cta="Confirm the change",
        reassurance=(
            "Didn&rsquo;t ask to change your email? Ignore this message and "
            "the address on your account stays as it is."
        ),
    ),
    # CODE ONLY - Supabase issues a bare nonce here, with no TokenHash and no
    # ConfirmationURL, so there is nothing a link could point at.
    "reauthentication.html": dict(
        dashboard_name="Reauthentication",
        subject="Confirm it's you",
        heading="Confirm it&rsquo;s you",
        lead=(
            "Enter this code to confirm the change you just asked for. We ask "
            "before anything that affects how you sign in."
        ),
        code_label="Confirmation code",
        otp_type=None,
        next_path=None,
        cta=None,
        reassurance=(
            "Didn&rsquo;t start this? Ignore this email and nothing changes - "
            "then change your password, because someone may know it."
        ),
    ),
}


def render(spec: dict) -> str:
    if spec["otp_type"] is None:
        link_section = ""
        token_note = (
            "CODE ONLY: Supabase issues a bare nonce for reauthentication -\n"
            "  there is no {{ .TokenHash }} and no link to build."
        )
    else:
        link = _link(spec["otp_type"], spec["next_path"])
        link_section = LINK_SECTION.format(link=link, cta=spec["cta"])
        token_note = (
            f"Carries BOTH the {{{{ .Token }}}} code and a {{{{ .TokenHash }}}} "
            f"link (type={spec['otp_type']})."
        )
    return SHELL.format(
        dashboard_name=spec["dashboard_name"],
        subject=spec["subject"],
        heading=spec["heading"],
        lead=spec["lead"],
        code_label=spec["code_label"],
        link_section=link_section,
        reassurance=spec["reassurance"],
        token_note=token_note,
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for filename, spec in TEMPLATES.items():
        (OUT / filename).write_text(render(spec), encoding="utf-8")
        print(f"wrote {filename}")


if __name__ == "__main__":
    main()
