"""Render every Supabase auth email from ONE theme.

WHY A GENERATOR RATHER THAN FIVE HAND-EDITED FILES

Because the drift already bit. `reset-password.html` and `confirm-signup.html`
were restyled and both lost - or never had - the `{{ .Token }}` placeholder,
while the app had moved to asking people to TYPE a code. The emails arrived
looking correct and carrying only a link, so every code field in the product
had nothing to fill it with. Five near-identical files invite exactly that: the
theme gets updated in one and the tokens in another.

Run:  python scripts/build_email_templates.py
Then paste each file into Supabase → Authentication → Email Templates.

WHICH APP CALL USES WHICH TEMPLATE - get this wrong and the right-looking email
is sent for the wrong flow:

  signUp()                      -> Confirm signup    (confirmation)
  signInWithOtp()               -> Magic Link        (magic_link)
  resetPasswordForEmail()       -> Reset Password    (recovery)
  reauthenticate()              -> Reauthentication  (reauthentication)
  updateUser({email})           -> Change Email      (email_change)

TOKENS, AND THE ONE THAT IS DIFFERENT

`{{ .Token }}` is the typed code and belongs in EVERY template - the product
offers a code path for all of them.

`{{ .TokenHash }}` builds a one-click link into /auth/confirm. Deliberately NOT
`{{ .ConfirmationURL }}`: that routes through Supabase's verify endpoint and
hands back a PKCE `?code=`, which only works in the browser that STARTED the
flow. Request on a laptop, open on a phone, and it fails.

REAUTHENTICATION HAS NO LINK. Supabase issues a bare nonce for it - there is no
TokenHash and no ConfirmationURL - so that template is code-only. Putting a link
in it produces a dead href, which is why it gets its own branch below rather
than an "optional" flag nobody would notice was off.
"""
from __future__ import annotations

import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "supabase" / "templates"

# One shared shell. The visual language mirrors the auth surface in
# frontend/src/components/auth-shell.tsx: a quiet zinc canvas, white rounded
# card, dimensional monochrome app icon, compact product badge, restrained type,
# and near-black primary actions. Everything important is inline because many
# email clients strip or only partially support embedded CSS.
SHELL = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="x-apple-disable-message-reformatting" />
  <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
  <meta name="color-scheme" content="light" />
  <meta name="supported-color-schemes" content="light" />
  <title>{subject}</title>
  <style>
    :root {{ color-scheme: light; supported-color-schemes: light; }}
    body, table, td, a {{ -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }}
    table, td {{ mso-table-lspace: 0pt; mso-table-rspace: 0pt; }}
    table {{ border-collapse: collapse !important; }}
    img {{ -ms-interpolation-mode: bicubic; }}
    @media only screen and (max-width: 620px) {{
      .email-shell-cell {{ padding: 16px 12px !important; }}
      .email-brand {{ padding: 28px 24px 16px !important; }}
      .email-body {{ padding: 8px 24px 32px !important; }}
      .email-title {{ font-size: 26px !important; line-height: 32px !important; }}
      .email-lead {{ font-size: 15px !important; line-height: 24px !important; }}
      .email-code-box {{ padding: 22px 12px !important; }}
      .email-code {{ font-size: 32px !important; line-height: 40px !important; letter-spacing: 7px !important; padding-left: 7px !important; }}
      .email-footer {{ padding: 22px 24px !important; }}
    }}
  </style>
</head>
<body bgcolor="#f4f4f5" style="margin:0;padding:0;width:100% !important;background-color:#f4f4f5;">
<!--
  Oreag - "{dashboard_name}" email template.

  Paste into: Supabase Dashboard -> Authentication -> Email Templates ->
  "{dashboard_name}".  Subject:  {subject}

  GENERATED by scripts/build_email_templates.py - edit that, not this file.
  {token_note}
-->
<div style="display:none;font-size:1px;color:#f4f4f5;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">
  {preheader}&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#f4f4f5" class="email-shell" style="width:100%;background-color:#f4f4f5;margin:0;font-family:Geist,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <tr>
    <td align="center" class="email-shell-cell" style="padding:40px 16px;">
      <!--[if mso]><table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]-->
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" class="email-card" style="width:100%;max-width:560px;background-color:#ffffff;border:1px solid #e4e4e7;border-radius:24px;overflow:hidden;box-shadow:0 8px 24px rgba(24,24,27,0.06);">
        <tr>
          <td align="center" class="email-brand" style="padding:32px 40px 18px 40px;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center">
              <tr>
                <td width="48" height="48" align="center" valign="middle" style="width:48px;height:48px;">
                  <img src="{{{{ .SiteURL }}}}/icon.png" width="48" height="48" alt="" style="display:block;width:48px;height:48px;border:0;border-radius:15px;box-shadow:0 8px 18px rgba(0,0,0,0.18);" />
                </td>
                <td style="padding-left:12px;font-size:20px;line-height:24px;font-weight:700;letter-spacing:-0.025em;color:#18181b;">
                  Oreag
                </td>
              </tr>
            </table>
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin-top:14px;">
              <tr>
                <td bgcolor="#fafafa" style="padding:5px 12px;background-color:#fafafa;border:1px solid #e4e4e7;border-radius:999px;font-size:11px;line-height:16px;font-weight:600;color:#71717a;text-align:center;">
                  RAG &amp; Memory API
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td class="email-body" style="padding:8px 40px 40px 40px;">
            <h1 class="email-title" style="margin:0 0 10px 0;font-size:28px;line-height:34px;font-weight:700;letter-spacing:-0.03em;color:#18181b;text-align:center;">{heading}</h1>
            <p class="email-lead" style="margin:0 auto 28px auto;max-width:430px;font-size:15px;line-height:24px;color:#71717a;text-align:center;">
              {lead}
            </p>
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;">
              <tr>
                <td align="center" bgcolor="#fafafa" class="email-code-box" style="padding:24px 16px;background-color:#fafafa;border:1px solid #e4e4e7;border-radius:14px;">
                  <div style="font-size:11px;line-height:16px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#71717a;">
                    {code_label}
                  </div>
                  <div class="email-code" style="margin-top:9px;padding-left:9px;font-family:'SFMono-Regular',Consolas,'Liberation Mono',Menlo,monospace;font-size:36px;line-height:44px;font-weight:700;letter-spacing:9px;color:#18181b;white-space:nowrap;font-variant-numeric:tabular-nums;">{{{{ .Token }}}}</div>
                </td>
              </tr>
            </table>
            <p style="margin:12px 0 0 0;font-size:12px;line-height:19px;color:#a1a1aa;text-align:center;">
              For your security, this code expires shortly and can only be used once.
            </p>
{link_section}
          </td>
        </tr>
        <tr>
          <td bgcolor="#fafafa" class="email-footer" style="padding:24px 40px;background-color:#fafafa;border-top:1px solid #e4e4e7;">
            <p style="margin:0 0 4px 0;font-size:12px;line-height:18px;font-weight:700;color:#3f3f46;text-align:left;">
              Security note
            </p>
            <p style="margin:0;font-size:13px;line-height:20px;color:#71717a;text-align:left;">
              {reassurance}
            </p>
          </td>
        </tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
      <p style="margin:20px 0 0 0;font-size:12px;line-height:19px;color:#a1a1aa;text-align:center;">
        Oreag &nbsp;&middot;&nbsp; RAG &amp; Memory as a Service<br />
        This is an automated security message. Replies are not monitored.
      </p>
    </td>
  </tr>
</table>
</body>
</html>
"""

# Rendered only for templates that HAVE a token hash. The divider carries its
# own "or" so the code and the link read as alternatives rather than steps.
LINK_SECTION = """
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;margin-top:26px;">
              <tr>
                <td width="45%" valign="middle"><div style="height:1px;background-color:#e4e4e7;font-size:1px;line-height:1px;">&nbsp;</div></td>
                <td width="10%" align="center" style="padding:0 12px;font-size:11px;line-height:16px;font-weight:700;color:#a1a1aa;white-space:nowrap;">OR</td>
                <td width="45%" valign="middle"><div style="height:1px;background-color:#e4e4e7;font-size:1px;line-height:1px;">&nbsp;</div></td>
              </tr>
            </table>

            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;margin-top:20px;">
              <tr>
                <td align="center" bgcolor="#18181b" style="background-color:#18181b;border-radius:12px;">
                  <a href="{link}"
                     style="display:block;padding:15px 24px;font-size:15px;line-height:20px;font-weight:700;color:#ffffff;text-align:center;text-decoration:none;border-radius:12px;white-space:nowrap;">
                    {cta} &nbsp;&#8594;
                  </a>
                </td>
              </tr>
            </table>

            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;margin-top:24px;">
              <tr>
                <td style="padding-top:18px;border-top:1px solid #e4e4e7;">
                  <p style="margin:0;font-size:12px;line-height:18px;font-weight:700;color:#52525b;">
                    Button not working?
                  </p>
                  <p style="margin:3px 0 0 0;font-size:12px;line-height:18px;color:#71717a;">
                    Copy and paste this URL into your browser:<br />
                    <a href="{link}" style="color:#18181b;text-decoration:underline;word-break:break-all;">{link}</a>
                  </p>
                </td>
              </tr>
            </table>
"""


def _link(otp_type: str, next_path: str) -> str:
    return (
        "{{ .SiteURL }}/auth/confirm"
        f"?token_hash={{{{ .TokenHash }}}}&type={otp_type}&next={next_path}"
    )


TEMPLATES = {
    "confirm-signup.html": dict(
        dashboard_name="Confirm signup",
        subject="Confirm your Oreag email",
        heading="Confirm your email",
        lead=(
            "Use the verification code below to finish setting up your "
            "Oreag account."
        ),
        code_label="Confirmation code",
        otp_type="signup",
        next_path="/dashboard",
        cta="Confirm my email",
        reassurance=(
            "If you didn&rsquo;t create an Oreag account, you can safely ignore "
            "this email. Nothing will be created unless the code or link is used."
        ),
    ),
    "magic-link.html": dict(
        dashboard_name="Magic Link",
        subject="Your Oreag sign-in code",
        heading="Your sign-in code",
        lead=(
            "Use the sign-in code below to continue to Oreag. You can also "
            "use the secure link."
        ),
        code_label="Sign-in code",
        otp_type="magiclink",
        next_path="/dashboard",
        cta="Sign in with one click",
        reassurance=(
            "If you didn&rsquo;t try to sign in, you can safely ignore this "
            "email. Your account remains secure."
        ),
    ),
    "reset-password.html": dict(
        dashboard_name="Reset Password",
        subject="Reset your Oreag password",
        heading="Reset your password",
        lead=(
            "Use the reset code below to choose a new password for your "
            "Oreag account."
        ),
        code_label="Reset code",
        otp_type="recovery",
        next_path="/auth/reset-password",
        cta="Reset my password",
        reassurance=(
            "If you didn&rsquo;t request a password reset, you can safely "
            "ignore this email. Your password will not change."
        ),
    ),
    "email-change.html": dict(
        dashboard_name="Change Email Address",
        subject="Confirm your new Oreag email",
        heading="Confirm your new email",
        lead=(
            "Use the verification code below to confirm your new email "
            "address."
        ),
        code_label="Confirmation code",
        otp_type="email_change",
        next_path="/settings/profile",
        cta="Confirm the change",
        reassurance=(
            "If you didn&rsquo;t request this change, ignore this message. The "
            "email address on your account will stay the same."
        ),
    ),
    # CODE ONLY - Supabase issues a bare nonce here, with no TokenHash and no
    # ConfirmationURL, so there is nothing a link could point at.
    "reauthentication.html": dict(
        dashboard_name="Reauthentication",
        subject="Confirm it's you",
        heading="Confirm it&rsquo;s you",
        lead=(
            "Use the verification code below to confirm this sensitive "
            "account change."
        ),
        code_label="Confirmation code",
        otp_type=None,
        next_path=None,
        cta=None,
        reassurance=(
            "If you didn&rsquo;t start this change, secure your account by "
            "changing your password. This request will expire automatically."
        ),
    ),
}


def render(spec: dict) -> str:
    if spec["otp_type"] is None:
        link_section = ""
        token_note = (
            "CODE ONLY: Supabase issues a bare nonce for reauthentication -\n"
            "  there is no {{ .TokenHash }} and no link to build."
        )
    else:
        link = _link(spec["otp_type"], spec["next_path"])
        link_section = LINK_SECTION.format(link=link, cta=spec["cta"])
        token_note = (
            f"Carries BOTH the {{{{ .Token }}}} code and a {{{{ .TokenHash }}}} "
            f"link (type={spec['otp_type']})."
        )
    return SHELL.format(
        dashboard_name=spec["dashboard_name"],
        subject=spec["subject"],
        preheader=spec["lead"],
        heading=spec["heading"],
        lead=spec["lead"],
        code_label=spec["code_label"],
        link_section=link_section,
        reassurance=spec["reassurance"],
        token_note=token_note,
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for filename, spec in TEMPLATES.items():
        (OUT / filename).write_text(render(spec), encoding="utf-8")
        print(f"wrote {filename}")


if __name__ == "__main__":
    main()
